### ISSUE TITLE
current user is nil after token authenticated

### ISSUE THREAD

**Issue by march23** [nsarno/knock#104]
Even when the user token is authenticated I can't have access to the current_user, it sets to nil.

If I try to do Knock::AuthToken.new(token: token).entity_for(User) it does find the resource. 

Rails 5

**Comment by samueldr** [comment]
Try either downgrading to `~>1.4.2` or tracking master, as in #102, you might be hitting a case fixed in #84, but that is still not up in rubygems.

**Comment by march23** [comment]
I had to downgrade to ~>1.4.2, tracking master result on the same issue, not sure why since the #82 supposed to fix it

**Comment by nsarno** [comment]
Could you provide a failing test? Thanks

**Comment by yunixon** [comment]
current_user returns nil me too on Rails 5.0.0.1, with 1.4.2 works

**Comment by gneale** [comment]
I also have this problem: First call sends current_user info and all the other times it sends nil. 
Using stock Rails 5.0.0.1 and Knock 1.5.
I downgraded to 1.4.2 and used authenticate instead of authenticate_user and it sends the user info every time as expected. I'm not good enough to provide a failing test for you. Do you want me to share the the code ?

**Comment by gneale** [comment]
Ok using master works perfectly, sorry.

**Comment by nsarno** [comment]
Feel free to reopen if you still encounter this issue in the latest version or master.

**Comment by romanos** [comment]
I'm still having this issue in master, btw. Hard to recreate, but I will try and post a test case here.

**Comment by sumitdey035** [comment]
I'm using version 2.1.1 and still getting nil on the first call of current_user.
