### ISSUE TITLE
Rails 5, "skip_before_action :authenticate_user" in every controller throw: "ArgumentError: Before process_action callback :authenticate_user has not been defined"

### ISSUE THREAD

**Issue by johnunclesam** [nsarno/knock#138]
I'm using **Rails 5** and if I use:

```ruby
  skip_before_action :authenticate_user, only: [:create]
```

in every controller (it doesn't matter which), Rails throw this error:

```ruby
"ArgumentError: Before process_action callback :authenticate_user has not been defined"
```

I fixed this temporarily by adding this:

```ruby
  skip_before_action :authenticate_user, only: [:create], raise: false
```

**Why this?**

The same problem people have here: https://github.com/plataformatec/devise/issues/4207

**Comment by nsarno** [comment]
Could you provide the code of your controller? If possible, a failing test would be even nicer 👍 

Thank you

**Comment by johnunclesam** [comment]
Oh, sorry @nsarno, I don't have an online demo and my code is just rails api 5 latest version default, simply controller `hello world` with basic code and `nsarno/knock` master on github or 2.1.

`before_action` works,

`skip_before_action` doesn't work.

**Comment by nsarno** [comment]
Having the code of your controller would still be helpful, otherwise I can only guess. Thank you

**Comment by johnunclesam** [comment]
You can try with every controller with before_action :authenticate_user

**Comment by bmichelsen** [comment]
Did you have a look at [this](https://github.com/plataformatec/devise/issues/4207#issuecomment-234577294) and [this](https://github.com/plataformatec/devise/issues/4207#issuecomment-234587685) from the same thread?

The last comment linked above also makes a reference to [clearance/issues/621](https://github.com/thoughtbot/clearance/issues/621) which further points to the [method](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L632) where this behavior occurs.

Basically, it's a Rails 5 feature (see [rails/rails#19029](https://github.com/rails/rails/pull/19029) which talks a bit about the reasoning behind it and [this commit](https://github.com/rails/rails/commit/8b88df94ebda2e829782f514ff51caeaf5e694dd) where it's merged). `skip_before_action`, `skip_after_action`, and `skip_around_action` will now raise an ArgumentError if the specified callback doesn't exist.

You can prevent these errors from showing with `raise: false` like you mentioned in your first comment since that lets  you opt out of the new behavior.

Did that help or did I completely miss the question?

**Comment by nsarno** [comment]
Thank you for your detailed answer @bmichelsen

**Comment by laaksomavrick** [comment]
Stumbled on this issue today. Same error, but I was calling `:authenticate_user!` instead of `:authenticate_user`. Be wary, folks here from googling!

**Comment by kevanmoothien** [comment]
This works for me: 
`before_action :authenticate_user!, except: :action_here`
